# Generated by Django 3.1.7 on 2021-04-01 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='train_tricket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Train_name', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(blank=True)),
                ('From', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Sirajganj', 'Sirajganj'), ('Bogura', 'Bogura')], max_length=300)),
                ('To', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Sirajganj', 'Sirajganj'), ('Bogura', 'Bogura')], max_length=300)),
                ('ammound', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_tricket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=200)),
                ('From', models.CharField(max_length=200)),
                ('To', models.CharField(max_length=200)),
                ('Date', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(max_length=100)),
                ('adult', models.IntegerField()),
                ('child', models.CharField(blank=True, max_length=4, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('txid', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
